version: '2.2'

services:
  elasticsearch-backend:
    build: jib-build-elasticsearch-0.0.1-SNAPSHOT
    container_name: elasticsearch-app
    ports:
      - 18080:8080
      - 18089:8089
    environment:
      - spring.elasticsearch.scheme=http
      - spring.elasticsearch.uris=elasticsearch
      - spring.elasticsearch.port=9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL:=http://elasticsearch:9300
#        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic



#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.2.0
#    container_name: logstash
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./config:/etc/logstash/conf.d
#    ports:
#      - "5000:5000"
#    networks:
#      - elknet

networks:
  elastic:

volumes:
  esdata:
    driver: local

