app:
  index:
    name: doc
    id: id
    date: date
    title: title
    author: author
    content: content
    subject: subject
  executor:
    poolSize: 1
    keepAlive: 60
    queueCapacity: max
    maxPoolSize: max

spring:
  elasticsearch:
    repositoriesEnabled: true
    uris: localhost
    port: 9200
    scheme: https
    user: elastic
    password: UxYpURPaqrRdKY6+dumY
    fingerprint: 8dd56581eaaa1c7c961f81f3229548884844bad482b7cf48287a0403dfd4d7cd
