app:
  index:
    name: doc
    id: id
    date: date
    title: title
    author: author
    content: content
    subject: subject
  executor:
    poolSize: 1
    keepAlive: 60
    queueCapacity: max
    maxPoolSize: max
